version: '3.3'
services:
  matrix-sms-bridge:
    image: folivonet/matrix-sms-bridge:latest
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./config/gammu-smsdrc
        target: /etc/gammu-smsdrc
      - type: bind
        source: ./data
        target: /data
      #devices:
      #- "/dev/ttyUSB1:/dev/ttyModem"
    environment:
      - CONFIG_LOCATION=/config/application.yml
      - GAMMU_CONFIG=/config/gammu-smsdrc
      #- SPRING_PROFILES_ACTIVE=initialsync
    networks:
      - local-kannel
    expose:
      - 8080
    restart: on-failure
  matrix-synapse:
    image: matrixdotorg/synapse:latest
    volumes:
      - type: bind
        source: ./synapse
        target: /data
    environment:
      - SYNAPSE_REPORT_STATS=false
      - UID=1000
      - GID=1000
    depends_on:
      - matrix-sms-bridge
    networks:
      - local-kannel
    ports:
      - 8008:8008

networks:
  local-kannel: