matrix:
  bot:
    mode: APPSERVICE
    username: smsbot
    trackMembership: ALL
  appservice:
    namespaces:
      users:
        - localpartRegex: "sms_[0-9]{6,15}"
      rooms:
        - localpartRegex: "sms_[0-9]{6,15}"
      aliases: [ ]

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.jdbc.JdbcRepositoriesAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration